# Generated by Django 4.0.3 on 2022-05-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('askme_q', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
